### For reference, see `/opt/open5gs/etc/orig/open5gs/`
smf:
  sbi:
    port: 7777
  gtpc:
  gtpu:
  pfcp:
  subnet:
    - addr: 10.45.0.1/16
    #- addr: cafe::1/64

  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844
  mtu: 1400
  freeDiameter: smf.conf

nrf:
  sbi:
    - name: nrf
      port: 7777
upf:
  pfcp:
    - name: upf

parameter:
max:
pool:
time: