version: '2.4'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  webui:
    image: openverso/open5gs-webui:2.2.3  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
  nrf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nrfd   
    restart : on-failure 
  nssf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nssfd   
    restart : on-failure 
  amf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-amfd
    restart: on-failure
  smf:
    image: openverso/open5gs:2.2.3
    command: open5gs-smfd    
    restart : on-failure 

  mme:
    image: openverso/open5gs:2.2.3
    command: open5gs-mmed
    restart: on-failure
    ports:
      - 36412:36412
  sgwc:
    image: openverso/open5gs:2.2.3
    command: open5gs-sgwcd
    restart : on-failure
  sgwu:
    image: openverso/open5gs:2.2.3
    command: open5gs-sgwud
    restart : on-failure
  upf:
    image: openverso/open5gs:2.2.3
    command: open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
  pcrf:
    image: openverso/open5gs:2.2.3
    command: open5gs-pcrfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  hss:
    image: openverso/open5gs:2.2.3
    command: open5gs-hssd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  udr:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    command: 
      - open5gs-udrd
  udm:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    command: 
      - open5gs-udmd
  ausf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-ausfd
    restart : on-failure
  pcf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-pcfd
    restart : on-failure
  
