version: '2.4'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  webui:
    build:
      context: ../../open5gs/
      dockerfile: Dockerfile.webui
      args:
        version: 2.1.7
    image: openverso/open5gs-webui:2.1.7  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
  nrf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-nrfd   
    restart : on-failure 
  amf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: 
      - open5gs-amfd 
    restart : on-failure
  smf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-smfd    
    restart : on-failure 
  mme:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-mmed
    restart: on-failure
    ports:
      - 36412:36412
#/sctp
  sgwc:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-sgwcd
    restart : on-failure
  sgwu:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-sgwud
    restart : on-failure
  upf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: ["open5gs-upfd", "-e","debug" ]
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
  pcrf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: ["open5gs-pcrfd","-e","debug" ]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  hss:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: open5gs-hssd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  udr:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    restart: on-failure
    command: 
      - open5gs-udrd
  udm:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    restart: on-failure
    command: 
      - open5gs-udmd
  ausf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: 
      - open5gs-ausfd
    restart : on-failure
  pcf:
    build:
      context: ../../open5gs/
      args:
        version: 2.1.7
    image: openverso/open5gs:2.1.7
    command: 
      - open5gs-pcfd
    restart : on-failure
  
  # uncomment to test with UERANSIM
  ###################
  gnb:
    build:
      context: ../../ueransim/
      dockerfile: Dockerfile
    image: openverso/ueransim:v3.1.0
    command: 
      - gnb
    privileged: true
    cap_add:
      - all
    environment:
      AMF_HOSTNAME: amf
      UE_HOSTNAME: ue
  ue:
    build:
      context: ../../ueransim/
      dockerfile: Dockerfile
    image: openverso/ueransim:v3.1.0
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: enodeb
