version: '2.4'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  webui:
    build:
      context: .
      dockerfile: Dockerfile.webui
      args:
        version: ${OPEN5GS_VERSION}    
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
  nrf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: open5gs-nrfd   
    restart : on-failure 
  amf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: 
      - open5gs-amfd
    restart : on-failure
  smf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: open5gs-smfd    
    restart : on-failure 
  mme:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: open5gs-mmed
    restart: on-failure
    ports:
      - 36412:36412
#/sctp
  sgwc:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: open5gs-sgwcd
    restart : on-failure
  sgwu:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: open5gs-sgwud
    restart : on-failure
  upf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: ["open5gs-upfd", "-e","debug" ]
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
  pcrf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: ["open5gs-pcrfd","-e","debug" ]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  hss:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    restart: on-failure
    command: open5gs-hssd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  udr:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    restart: on-failure
    command: 
      - open5gs-udrd
  udm:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    restart: on-failure
    command: 
      - open5gs-udmd
  ausf:
    build:
      context: .
      args:
        version: ${OPEN5GS_VERSION}
    command: 
      - open5gs-ausfd
    restart : on-failure
  
  enodeb:
    build:
      context: ../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_04_1
    command: 
      - enb
    privileged: true
    cap_add:
      - all
    environment:
      MME_HOSTNAME: mme
      UE_HOSTNAME: ue

  ue:
    build:
      context: ../srs-lte/
      dockerfile: Dockerfile
    image: openverso/srs-lte:20_04_1
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: enodeb
    #network_mode: "service:enodeb"
